Boilerplate
iBaryo/gigya-cdp-cli pull request #6
Opened 2020-12-03 12:36 UTC by yourgirlcodes

WIP for CLI CR - 
working on direct appplication and segments, update in audiences for cleaner code

2020-12-25 10:55 UTC, yourgirlcodes commented
PR for updates before demo

2021-01-01 20:01 UTC, iBaryo commented
so this can be closed for the next PR?
https://github.com/iBaryo/gigya-cdp-cli/pull/7

2021-01-03 11:13 UTC, yourgirlcodes commented
Newest for CR

2021-01-07 14:30 UTC, iBaryo requested changes

2021-01-07 14:30 UTC, iBaryo commented on defaultSchemaFakers.json
> +{"config":{"primaryPhone":"tyre","primaryEmail":"name"},"password":""}
remove this file

2021-01-07 14:30 UTC, iBaryo commented on boilerplateFakers.json
> +{"config":{"primaryEmail":"email","primaryPhone":"phoneNumber","purchasePrice":"price","orderId":"uuid","sessionTime":"number","pageUrl":"url"},"password":""}
remove this file

2021-01-07 14:50 UTC, merged